apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: iyyx7e7qy-go 
  janus-idp.io/tekton: iyyx7e7qy-go
  backstage.io/kubernetes-id: iyyx7e7qy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iyyx7e7qy-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml