apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iyyx7e7qy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iyyx7e7qy-go 
  name: iyyx7e7qy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iyyx7e7qy-go 
